sonar.organization=isramss
sonar.projectKey=isramss_simplon-cda-projet-WedPresta_backend
sonar.projectName=backend-wedPresta

sonar.sources=.
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,server.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info